#!/usr/bin/env holen
---
desc: A tiny, pure and fast implementation of Clojure in Clojure for shell scripting.
strategies:
    binary:
        base_url: https://github.com/borkdude/babashka/releases/download/v{{.Version}}/babashka-{{.Version}}-{{.OSArchData.tag}}.zip
        unpack_path: bb
        os_arch:
            linux_amd64:
                tag: linux-amd64
            darwin_amd64:
                tag: macos-amd64
        versions:
          - version: '0.0.13'
            os_arch:
                linux_amd64:
                    sha256sum: 282cfd188f5da18a0e733aa835052da38399a567b615b5a1733d85466584a5f7
                darwin_amd64:
                    sha256sum: d95da1eef11cf25332ac15038e9864984a907f47fb5215b7afedaa3daea1eadf
          - version: '0.0.9-2'
            os_arch:
                linux_amd64:
                    sha256sum: 35e4857e0e5e8ed1f78e20c5e35e53fdfc820eccbbd1dd6a66245eccce7de044
                darwin_amd64:
                    sha256sum: c0b2384f461a09e2b529ad704f757d70e2664cd3c6b2a96fb9b59b9f4babe7e6
          - version: '0.0.8'
            os_arch:
                linux_amd64:
                    sha256sum: 8297f50ed88fa047b870a9acdb58ef40c4d92a5a45a05a6a9aedeaffd19175e0
                darwin_amd64:
                    sha256sum: 7dc12cda427823b82a02fcd6046fa5f08d6190c5a8632d53aadb671042b77685
          - version: '0.0.7'
            os_arch:
                linux_amd64:
                    sha256sum: cae14221af45129b4b13aa6a877bf7271aa38fdc85a6091a4e67ece9ad5fbd76
                darwin_amd64:
                    sha256sum: 78125fe035c17555b3b6abea6aaf0b5deaf1449639b554f9718365923e703fa0
          - version: '0.0.5'
            os_arch:
                linux_amd64:
                    sha256sum: d7898234b83d2695c5d0852c5f57d92a12d866efef64e5ddbd5fc090dcce9214
                darwin_amd64:
                    sha256sum: be3a1246a5647de5e7fec7e402c0ed6c5e3dabc08360ccc280c6c2e3c539c4be
