#!/usr/bin/env holen
---
desc: Visualizing Docker data
strategies:
    docker:
        image: nate/dockviz:v{{.Version}}
        docker_conn: true
        versions:
          - version: '0.4.2'
          - version: '0.4.1'
    binary:
        base_url: https://github.com/justone/dockviz/releases/download/v{{.Version}}/dockviz_{{.OSArch}}
        versions:
          - version: '0.4.2'
          - version: '0.4.1'
...
