#!/usr/bin/env holen
---
desc: One of a suite of programs to use native stores to keep Docker credentials safe.
strategies:
    binary:
        base_url: https://github.com/docker/docker-credential-helpers/releases/download/v{{.Version}}/docker-credential-osxkeychain-v{{.Version}}-amd64.tar.gz
        unpack_path: docker-credential-osxkeychain
        versions:
          - version: '0.5.0'
            os_arch:
                darwin_amd64:
                    sha256sum: 72db29f4443cab79c761bf6fad695cf948e27afcc0ad5a7246597998e0efff51
