#!/usr/bin/env holen
---
desc: A tool for defining and running multi-container Docker applications.
strategies:
    binary:
        base_url: https://github.com/docker/compose/releases/download/{{.Version}}/docker-compose-{{.OSArchData.ext}}
        os_arch:
            linux_amd64:
                ext: Linux-x86_64
            darwin_amd64:
                ext: Darwin-x86_64
        versions:
          - version: '1.23.2'
            os_arch:
                linux_amd64:
                    sha256sum: 4d618e19b91b9a49f36d041446d96a1a0a067c676330a4f25aca6bbd000de7a9
                darwin_amd64:
                    sha256sum: c7e900cdfcd1e60dc6828e399473b46e7070acab514472fe91aac4130d9deb58
          - version: '1.21.0'
            os_arch:
                linux_amd64:
                    sha256sum: af639f5e9ca229442c8738135b5015450d56e2c1ae07c0aaa93b7da9fe09c2b0
                darwin_amd64:
                    sha256sum: 6cadd64afbd1606e1517b91df591a0104c882a2343865aaa9c7ad9dcae81faf5
          - version: '1.19.0'
            os_arch:
                linux_amd64:
                    sha256sum: 78734996d716113f9f9716d0b5064166e9475835e5000fd01b0480d19e1f7372
                darwin_amd64:
                    sha256sum: e3c802584bf40eb3e92ac082f3d3217d940c234b80b686510ede977c90d0715e
          - version: '1.9.0'
            os_arch:
                linux_amd64:
                    sha256sum: eeca988428d29534fecdff2768fa2e8c293b812b1c77da8ab5daf7f441c92e5b
                darwin_amd64:
                    sha256sum: ce56a5c6702e97e09bf92253a1ffd2ff2afb1f4a9c9ce778ea9a54bf1fdab517
          - version: '1.8.0'
          - version: '1.7.1'
...
