#!/usr/bin/env holen
---
desc: Command line interface for running commands against Kubernetes clusters
strategies:
    binary:
        base_url: https://storage.googleapis.com/kubernetes-release/release/v{{.Version}}/bin/{{.OS}}/{{.Arch}}/kubectl{{.OSArchData.ext}}
        os_arch:
            windows_amd64:
                ext: .exe
        versions:
          - version: '1.15.1'
            os_arch:
                linux_amd64:
                    sha256sum: f4f4b855ab16ef295bc74f07edc77482d43e8fe81abc7cf92c476c4344788aa6
                darwin_amd64:
                    sha256sum: 7d988cd758b8f46721430454f2cc94d511112f183a5ebab9a84a8a8f1d14b36d
                windows_amd64:
                    sha256sum: d1f41a7a49e5528a20514c30159039e10d453cf4edcdfeabb0e880c6587a45bb
          - version: '1.14.2'
            os_arch:
                linux_amd64:
                    sha256sum: 9daf696f5609ab41ac491886de5e87e35d8d3076f65defc27602a476800a97bf
                darwin_amd64:
                    sha256sum: b5faa4915076719742ef0f81245a34d1692658108240dced6d7fd5ef9e673dc0
                windows_amd64:
                    sha256sum: f1a397f56d5078009f348cbf23265c191e87e4a05ba5ebd54c53178ce685de01
          - version: '1.8.2'
            base_url: https://dl.k8s.io/v{{.Version}}/kubernetes-client-{{.OS}}-{{.Arch}}.tar.gz
            unpack_path: kubernetes/client/bin/kubectl{{.OSArchData.ext}}
            os_arch:
                linux_arm:
                    sha256sum: a1cff2f8ab5f77f000e20f87b00a3723a8323fec82926afcc984722ab3f8d714
                linux_amd64:
                    sha256sum: 7c20d4a3859c07aadf9a1676876bafdf56187478a69d3bfca5277fb275febb96
                darwin_amd64:
                    sha256sum: 15da279f018a73f93b857639931c4ba8a714c86e5c5738c33840c47df44ac2a4
                windows_amd64:
                    sha256sum: b8ff337615f740b1501cf7284d7f0a51a82880dcf23fff2464f8d37045c27f3f
