#!/usr/bin/env holen
---
desc: Fast, secure, efficient backup program
min_holen_version: v0.4.0
strategies:
    binary:
        base_url: https://github.com/restic/restic/releases/download/v{{.Version}}/restic_{{.Version}}_{{.OSArch}}{{.OSArchData.dlext}}
        unpack_path: restic_{{.Version}}_{{.OSArch}}{{.OSArchData.fileext}}
        os_arch:
            linux_amd64:
                dlext: .bz2
            darwin_amd64:
                dlext: .bz2
            windows_amd64:
                ext: .exe
                dlext: .zip
        versions:
          - version: '0.9.2'
            os_arch:
                linux_amd64:
                    sha256sum: 1ad8a76a9f966da5f7a319c49a6db071a60ebaa24d69e6d86d53d6f2bcaf11ed
                darwin_amd64:
                    sha256sum: 53b0a342de5344ef3ec73bbf644da0abe178532e67672bc943ab29662c2b8292
                windows_amd64:
                    sha256sum: 82e0dfe67afecbff60f4442ca4595984ad82b8515c985857ac067eb4b1737f52
