#!/usr/bin/env holen
---
desc: Terraform is a tool for building, changing, and combining infrastructure safely and efficiently.
strategies:
    binary:
        base_url: https://releases.hashicorp.com/terraform/{{.Version}}/terraform_{{.Version}}_{{.OSArch}}.zip
        unpack_path: terraform
        versions:
          - version: '0.7.11'
            os_arch:
                linux_amd64:
                    sha256sum: 1a1aa419d614ea38d93cc751e00874ace9414184c75e66480384c464e8a634db
                darwin_amd64:
                    sha256sum: 69c8d2b07f04e9bf0beb4a333dd189d8616d22fe46692bdb5aef10493ac5e5c6
