#!/usr/bin/env holen
---
desc: Terraform is a tool for building, changing, and combining infrastructure safely and efficiently.
strategies:
    docker:
        image: hashicorp/terraform:{{.Version}}
        pwd_workdir: true
        mount_pwd: true
        versions:
          - version: '0.8.1'
          - version: '0.8.0'
          - version: '0.7.11'
    binary:
        base_url: https://releases.hashicorp.com/terraform/{{.Version}}/terraform_{{.Version}}_{{.OSArch}}.zip
        unpack_path: terraform
        versions:
          - version: '0.8.1'
            os_arch:
                linux_amd64:
                    sha256sum: da98894a79b7e97ddcb2a1fed7700d3f53c3660f294fb709e1d52c9baaee5c59
                darwin_amd64:
                    sha256sum: 275104513600bf50a28942131d928d2be405c75f9f36a9c722718500075856a1
          - version: '0.8.0'
            os_arch:
                linux_amd64:
                    sha256sum: 9f99258396dad71746fb96036bf421e05fb3f36f402b89c3f16b453f3f0ee9cf
                darwin_amd64:
                    sha256sum: 4f4410be73200f95f84e359409481c8c48bc70e659fc5f7ea3f33a1db574ff65
          - version: '0.7.11'
            os_arch:
                linux_amd64:
                    sha256sum: 1a1aa419d614ea38d93cc751e00874ace9414184c75e66480384c464e8a634db
                darwin_amd64:
                    sha256sum: 69c8d2b07f04e9bf0beb4a333dd189d8616d22fe46692bdb5aef10493ac5e5c6
